// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmnbpszju6jleTBQ5-cIyqt1jt5n_lEvY',
    appId: '1:84523857044:android:fe7ee97fe9d41bdd03f081',
    messagingSenderId: '84523857044',
    projectId: 'femora-258cf',
    storageBucket: 'femora-258cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1msjwp3-OkygVO6eAp7zSHh9S2wDfhUc',
    appId: '1:84523857044:ios:440a471d33a36b1d03f081',
    messagingSenderId: '84523857044',
    projectId: 'femora-258cf',
    storageBucket: 'femora-258cf.firebasestorage.app',
    androidClientId: '84523857044-694sujqg5kv9q8fb0vge8hhh082vp64c.apps.googleusercontent.com',
    iosClientId: '84523857044-h9mbj13mjqk2s3qblfh2hdtohfvbco81.apps.googleusercontent.com',
    iosBundleId: 'com.example.femora',
  );

}